[package]
name = "raytracing_in_one_weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
image = "0.24.6"
rand = "0.8.5"
vulkano = "0.33.0"

[profile.dev]
opt-level = 1
