#version 460

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D img;

// TODO: optimize aligment
layout (push_constant) uniform PushConstantData {
    vec3 origin;
    vec3 lower_left_corner;
    vec3 horizontal;
    vec3 vertical;
    vec3 u;
    vec3 v;
    vec3 w;
    float lens_radius;
} camera;

#define BOUNCE_AMOUNT 1


float check_hit(vec3 ray_origin, vec3 ray_direction, float t_min, float t_max) {
    return -1.0; // miss
}

void main() {
    // UV
    vec2 uv = (gl_GlobalInvocationID.xy + vec2(0.5)) / vec2(imageSize(img));
    //TODO: ADD random offseting

    // calculate ray;
    vec3 rd = camera.lens_radius * vec3(0.0); //TODO: add random numbers
    vec3 ray_offset = camera.u * rd.x + camera.v * rd.y;
    vec3 ray_origin = camera.origin + ray_offset;
    vec3 ray_direction = camera.lower_left_corner + uv.x * camera.horizontal + uv.y * camera.vertical - camera.origin - ray_offset;

    // initialize color
    vec3 pixel_color = vec3(0.0);

    // bounces
    for (int bounce = 0; bounce < BOUNCE_AMOUNT; bounce++) {
        if (check_hit(ray_origin, ray_direction, 0.001, 1. / 0.) > 0.0) {

        }
        else {
            // sky gradient
            float t = 0.5 * (normalize(ray_direction).y + 1.0);
            pixel_color = mix(vec3(1.0), vec3(0.5, 0.7, 1.0), t);
        }
    }


    imageStore(img, ivec2(gl_GlobalInvocationID.xy), vec4(pixel_color, 1.0));
}