#version 460

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D img;

struct Ray{
    vec3 origin;
    float padding1;
    vec3 direction;
    float padding2;  
};

layout (std140, set = 0, binding = 1) readonly buffer RaysIn {
    Ray rays[];
};

struct Sphere{
    vec3 center;
    float radius;
    vec3 padding;
    uint material_index;
};

layout(std140,set = 0, binding = 2) readonly buffer SpheresIn {
    Sphere spheres[];
};

layout(push_constant) uniform PushConstantData{
    uint sphere_amount;
} limits;


bool check_hit(Ray ray, float t_min, float t_max, Sphere sphere) {
    // quadratic setup
    vec3 oc = ray.origin - sphere.center;
    float a = length(ray.direction);
    a *= a;
    float half_b = dot(oc, ray.direction);
    float c = length(oc)*length(oc) - sphere.radius*sphere.radius;

    // check if there are real solutions
    float discriminant = half_b*half_b - a*c;
    if( discriminant < 0.0 ){
        return false;
    }
    float sqrtd = sqrt(discriminant);

    // find the nearest root in the acceptable range
    float root = (-half_b - sqrtd) /a;
    if(root < t_min || root > t_max ){
        root = (-half_b + sqrtd) /a;
        if(root < t_min || root > t_max){
            return false;
        }
    }

    return true; // miss
}


bool get_closest_hit(Ray ray, float t_min, float t_max){
    bool hit_anything = false;
    float closest_so_far = t_max;

    for(uint i=0; i<limits.sphere_amount; i++){
        if(check_hit(ray, t_min, closest_so_far, spheres[i])){
            hit_anything = true;
        } 
    }

    return hit_anything;
}


// #define BOUNCE_AMOUNT 1

void main() {

    // initialize color
    vec3 pixel_color = vec3(0.0);

    //Get ray
    uint index = gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x + gl_GlobalInvocationID.x;
    Ray ray =  rays[index];



    // bounces
    // for (int bounce = 0; bounce < BOUNCE_AMOUNT; bounce++) {
        if (get_closest_hit(ray, 0.001, 1. / 0.)) {

        }
        else {
            // sky gradient
            float t = 0.5 * (normalize(ray.direction).y + 1.0);
            pixel_color = mix(vec3(1.0), vec3(0.5, 0.7, 1.0), t);
        }
    // }

    imageStore(img, ivec2(gl_GlobalInvocationID.xy), vec4(pixel_color, 1.0));
}